version: '3.9'

services:
  # 🧱 Backend NestJS
  backend:
    container_name: examhub-backend
    build: .
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/examhub
      AWS_REGION: ap-southeast-1
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: 12345678
      AWS_S3_BUCKET: exam-hub-uploads
      MINIO_ENDPOINT: http://minio:9000
      NODE_ENV: development
    depends_on:
      - db
      - minio
    volumes:
      - .:/app
    command: npm run start:dev

  # 🐘 PostgreSQL
  db:
    container_name: examhub-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: examhub
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 🧰 pgAdmin (giao diện web xem database)
  pgadmin:
    container_name: examhub-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - '5050:80'
    depends_on:
      - db

  # 📦 MinIO (giả lập AWS S3)
  minio:
    container_name: examhub-minio
    image: quay.io/minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - minio_data:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio_data:
